#! /usr/bin/bash

git add .
git status
echo -n "Enter the Description for the Change: " [Minor Update]
read CHANGE_MSG
git commit -m "${CHANGE_MSG}"
notify-send 'Git Update' 'Setup updating.'
git push origin master
notify-send "Git Update" "Setup Updated"
