directory: ~/Music
library: ~/.config/beets/library.db

import:
    move: yes
    write: yes
    autotag: yes
    timid: no
    resume: ask
    incremental: no
    none_rec_action: ask
    quiet: no
    quiet_fallback: skip
    default_action: apply

original_date: yes
per_disc_numbering: no
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg"]
ignore: [".*", "*~", "System Volume Information"]
threaded: yes
timeout: 5.0
verbose: no
color: yes
terminal_encoding: utf8

paths:
    default: $albumartist/$album/$title
    singleton: Non-Album/$artist - $title

plugins: chroma fromfilename fetchart embedart ftintitle lastgenre mpdstats mpdupdate

chroma:
    auto: no
mpd:
    host: localhost
    port: 6600

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
path_sep_replace: _
    
match:
    strong_rec_thresh: 0.1      # match 90% or better for auto import
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    track_length_grace: 10
    track_length_max: 30

